### ISSUE TITLE
Potential breaking changes not documented on CHANGELOG.md

### ISSUE THREAD

**Issue by kw7oe** [aws-beam/aws-elixir#101]
Hi all, just wanted to raise up an issue where a potential breaking changes is not documented in CHANGELOG.md. 

In short, we found out that the error response of `v0.5.0` is different compared to `v.0.9.2` when attempting to update our dependencies:

```elixir
# v0.5.0
{:error, {exception, message}}

# v0.9.2
{:error, {:unexpected_response, response}}
```

After some deep dive, here's the file changes related: 

- Latest: https://github.com/aws-beam/aws-elixir/blob/0ee85f3e745d73e05a986eca279d89965a4db9f7/lib/aws/request.ex#L51
- Older: https://github.com/aws-beam/aws-elixir/blob/630970a4a0d75ec0c9e4e6e24a6005d549e3325a/lib/aws/cognito_identity_provider.ex#L576

It seems like the changes happen after `v0.7.0` according to this [commit](https://github.com/aws-beam/aws-elixir/commit/c72a7d151218dc1c8ae8d5173080aabea8e02813). 

Am I right in regards of this as a breaking changes? If so, would it be good for us to update the CHANGELOG.md to document the breaking changes? 

Happy to send a PR in and thanks for the amazing work as well 🎉

**Comment by philss** [comment]
@kw7oe my bad :sweat_smile: 
Yeah, It makes sense to document this. Please go ahead with the PR :+1: 
And thank you! :purple_heart:

**Comment by kw7oe** [comment]
All good @philss 👍🏻, no worry! It's just an oversight. Things happen, so nothing to sorry about.

I'll close this first since the PR is in! 

Once again, thanks for all the work on this library 💯
