### ISSUE TITLE
Add Support for AWS Textract Analyzing ID Documents feature

### ISSUE THREAD

**Issue by Sahedeva** [aws-beam/aws-elixir#103]
On December 1st 2021 Amazon announced a new feature for their Textract service - Analyze ID. This allows for extracting data from government issued ids (i.e. Driver's license). Multiple languages SDKs support this new feature. Aws-elixir Textract module does not.

Please add support for this.

https://aws.amazon.com/blogs/machine-learning/announcing-support-for-extracting-data-from-identity-documents-using-amazon-textract/

**Comment by philss** [comment]
@Sahedeva this update is now available in the version 0.10.0 that was just released.

**Comment by Sahedeva** [comment]
@philss just a quick update, I have successfully used the analyze_id feature using 0.10.0 - thank you so much for making this happen!
