### ISSUE TITLE
Update hex package, which currently points to jkakar/aws-elixir

### ISSUE THREAD

**Issue by andreaazzini** [aws-beam/aws-elixir#13]
The title should be self explanatory, but when running `mix deps.get` on a project that uses `:aws ~> 0.5.0` as a dependency, the old `jkakar/aws-elixir` is fetched instead of `aws-beam/aws-elixir`.

This may cause dependency conflicts. For instance, I need `httpoison ~> 1.5`, but `jkakar/aws-elixir` specify older dependency versions (in this case `httpoison ~> 0.11.1`).

**Comment by aerosol** [comment]
Much anticipated improvement

**Comment by jfacorro** [comment]
The [latest released version](https://hex.pm/packages/aws) of the package points to this repository now.
