### ISSUE TITLE
0.5.1? Is New Tag for Session Token coming?

### ISSUE THREAD

**Issue by robotarmy** [aws-beam/aws-elixir#18]
Hi- I see the session_token code on master and i've confirmed that it works - and that i'm unable to use the client without this token.

Is a updated tag available for this?

**Comment by mrallen1** [comment]
I tried to publish a new package to hex today but I got some weird errors from the process and I don't really know how to fix them. Hey @tsantero can you give me a hand here?

**Comment by jfacorro** [comment]
I was able to publish a new [v0.6.0](https://hex.pm/packages/aws) version to hex.pm.
