### ISSUE TITLE
Get container credentials from relative URI when running in ECS

### ISSUE THREAD

**Issue by zatchheems** [aws-beam/aws-elixir#204]
Thank you for your continued work and maintenance on this library! I use this client to fetch values from AWS SecretsManager after my instance spins up.

**To get to the point:** other AWS clients such as the [JavaScript AWS SDK](https://github.com/aws/aws-sdk-js-v3) and [Python BOTO3 SDK](https://github.com/boto/boto3) fetch credentials for initializing a client from within an ECS container by way of the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable. 

Would others find it useful to use Hackney to GET credentials from the container credentials relative URI when running a containerized Elixir project within AWS? I currently have a workaround for this using the following (uses HTTPoison which wraps Hackney and would be trivial to rewrite using `AWS.HTTPClient.Hackney`):

```elixir
@ecs_container_internal_ip "http://169.254.170.2"

# Needs a check to see if access_key_id and secret_access_key are set.
# If above vars are unset, use relative credentials URI given to us within ECS to get access key ID and secret key
with container_credentials_relative_uri <- System.get_env("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"),
     %HTTPoison.Response{status_code: 200, body: body} <- HTTPoison.get!(@ecs_container_internal_ip <> container_credentials_relative_uri),
     %{
       "AccessKeyId" => access_key_id,
       "SecretAccessKey" => secret_access_key,
       "Token" => token
     } <- Jason.decode!(body) do

  AWS.Client.create(access_key_id, secret_access_key, token, region)
else
  err ->
    # Error handling, etc.
end
```

Just wondering if others are using this client similarly and if so, if this functionality would be a welcome addition to the library to reach some kind of feature parity with clients built in other languages. As with the other clients, this work may also need to support EKS usage as well as that has a different internal IP (`169.254.170.23` or `[fd00:ec2::23]`).

**Comment by onno-vos-dev** [comment]
Hi @zatchheems Quick reply but can expand on this tomorrow but depending on your timezone you may be getting what you need from my reply alone. 

Wouldn't the `aws_credentials_ecs` from aws_credentials (https://github.com/aws-beam/aws_credentials) do what you're proposing here? 🤔

**Comment by zatchheems** [comment]
No need to expand on your reply (and I get it, I'm busy too!).

That library does _exactly_ what I'm proposing here—one of its features is literally to fall back to `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` if credentials aren't specified.

If I knew that library existed I would have used it. Thanks!
