### ISSUE TITLE
Wrong parameter name in Mturk error messages

### ISSUE THREAD

**Issue by 4knahs** [aws-beam/aws-elixir#3]
The [error messages](https://github.com/aws-beam/aws-elixir/blob/master/lib/aws/mechanical_turk.ex#L598) in mturk are always `nil`. Looking at the actual HTTPoison response from `create_additional_assignments_for_h_i_t\3`: 

```
%HTTPoison.Response{
    body:
      "{\"__type\":\"ParameterValidationError\",\"Message\":\"The value 0 is invalid for MaxAssignmentIncrement. Valid values range from 1 to 1000000000. (1523017679385 s)\",\"Parameter\":\"MaxAssignmentIncrement\",\"TurkErrorCode\":\"AWS.ParameterOutOfRange\"}",
    headers: [
      {"x-amzn-RequestId", "fd299fbe-5dc7-4f08-8ed3-1c79b545725a"},
      {"Content-Type", "application/x-amz-json-1.1"},
      {"Content-Length", "238"},
      {"Date", "Fri, 06 Apr 2018 12:27:59 GMT"},
      {"Cneonction", "close"}
    ],
    status_code: 400
  }
```

and looking at the [code](https://github.com/aws-beam/aws-elixir/blob/master/lib/aws/mechanical_turk.ex#L598) it seems that the error message field is wrong since it should start with a capital:

```
{:ok, response=%HTTPoison.Response{body: body}} ->
        error = Poison.Parser.parse!(body)
        exception = error["__type"]
        message = error["message"]
        {:error, {exception, message}}
```

It should be `message = error["Message"]` instead.

**Comment by mrallen1** [comment]
Thanks for the message. This code is autogenerated by [aws-codegen](https://github.com/aws-beam/aws-codegen), so it is likely an error in the template which assembled this module for this API.

That's more than I have time to manage today but I will look into it.

**Comment by 4knahs** [comment]
I correct my previous statement, the error messages aren't always `nil`.

Apparently the first letter case is arbitrary across requests.. Here is a response body to `AWS.MechanicalTurk.list_h_i_ts\3` with lower case:

```
%HTTPoison.Response{
    body:
      "{\"__type\":\"ValidationException\",\"message\":\"1 validation error detected: Value '1000' at 'maxResults' failed to satisfy constraint: Member must have value less than or equal to 100\"}",
    headers: [
      {"x-amzn-RequestId", "4481aec4-ac71-4517-bbb8-3d3125440041"},
      {"Content-Type", "application/x-amz-json-1.1"},
      {"Content-Length", "181"},
      {"Date", "Mon, 09 Apr 2018 10:22:03 GMT"},
      {"nnCoection", "close"}
    ],
    status_code: 400
  }
```

**Comment by jfacorro** [comment]
@4knahs Do you know if this applies only to the mturk integration or to all of them?

**Comment by jfacorro** [comment]
After some investigation the shape of the error depends on the API being used and the specific error returned. A possible approach is the one described [here](https://github.com/aws-beam/aws-codegen/issues/23) which involved returning the full (decoded) error.

**Comment by 4knahs** [comment]
Sorry for the late reply. From what i recall i tested just mturk, haven't touched that code in a long time though.

**Comment by jfacorro** [comment]
The clients are returning the whole parsed error in latest `master` now to avoid having to figure out the different paths to the message and code.
