### ISSUE TITLE
NXDOMAIN - endpoint

### ISSUE THREAD

**Issue by ulutomaz** [aws-beam/aws-elixir#4]
Hi, 

i am having issues with connection to Kinesis. It looks like the endpoint you have as a default is wrong. 
Same problem was at Boto library. `amazonaws.com` is wrong. 

But I can't find a way to override this endpoint at Client initialisation.

```
client = %AWS.Client{access_key_id: "secret",
                     secret_access_key: "secret",
                     region: "eu-west-1",
                     endpoint: "kinesis.eu-west-1.amazonaws.com"}


AWS.Kinesis.list_streams(client, %{})
``` 

Returns:
```
{:error, %HTTPoison.Error{id: nil, reason: :nxdomain}}
```

Best,
Tomaz

**Comment by ulutomaz** [comment]
Not really an issue anymore. Fixed. Can close the case.

**Comment by mrallen1** [comment]
OK, thanks
