### ISSUE TITLE
Unknow error on aws iot 

### ISSUE THREAD

**Issue by RandomGuy2020** [aws-beam/aws-elixir#47]
Hi ! I'm a newbie on elixir so maybe it's an easy problem ^^ I'm trying to create a policy in iot core so:
I'm trying to use the fuction create_policy(client, "policyName", **input**)  but I don't found an example to know how I have to write **input**  correctly, I have an issue {error,nil} and except the input format I don't know what can be the problem because I can make a get_policy(client, "policyName") and it's working.

So if someone can send me an example of the fonction create_policy it can be great !

Thanks and have a nice day.

**Comment by philss** [comment]
Hi, @RandomGuy2020! Thanks for opening the issue.
The **input** value is a policy like the one in the example: https://docs.aws.amazon.com/cli/latest/reference/iot/create-policy.html#examples

We are investigating how to improve our docs to include some examples like these.

**Comment by RandomGuy2020** [comment]
Thanks for you quick reply! I'm very sorry but i'm very bad and it doesn't work when you will have time could you see the code below and say to me what's is wrong ?
Here is the code (I replace the 000000000000 by my id account) : 
`
    client1 = initClient()

    input = %{
    "Version": "2012-10-17",
    "Statement": [
        %{
            "Effect": "Allow",
            "Action": [
                "iot:Publish",
                "iot:Receive"
            ],
            "Resource": [
                "arn:aws:iot:us-west-2:000000000000:topic/topic_1",
                "arn:aws:iot:us-west-2:000000000000:topic/topic_2"
            ]
        },
        %{
            "Effect": "Allow",
            "Action": [
                "iot:Subscribe"
            ],
            "Resource": [
                "arn:aws:iot:us-west-2:000000000000:topicfilter/topic_1",
                "arn:aws:iot:us-west-2:000000000000:topicfilter/topic_2"
            ]
        },
        %{
            "Effect": "Allow",
            "Action": [
                "iot:Connect"
            ],
            "Resource": [
                "arn:aws:iot:us-west-2:000000000000:client/basicPubSub"
            ]
        }
    ]
}
    
    AWS.IoT.create_policy(client1, "testelixir", input)`

Thanks you for your time 😄

**Comment by philss** [comment]
@RandomGuy2020 I think you need to send the **input** as a JSON string, because it won't be converted automatically. Can you give a try and check if works?

**Comment by RandomGuy2020** [comment]
It doesn't work too when I use 

`input=Poison.encode!(...) `

And the error is still {:error, nil}

**Comment by philss** [comment]
@RandomGuy2020 can you try to create the same policy using AWS console?
Also, do you see warnings when you try to create the policy?

**Comment by RandomGuy2020** [comment]
It's working on aws console

**Comment by philss** [comment]
OK, thank you! One more try: would you mind to use the GitHub version and see if works?
Just change your `mix.exs` to point to this repository: `{:aws, github: "aws-beam/aws-elixir"}`.

**Comment by RandomGuy2020** [comment]
Ok now I have an error 400, when I let the Poison.encode!(..) I don't have a message for the error but when I remove it I always have an error 400 but the body error is : \"message\":\"1 validation error detected: Value null at 'policyDocument' failed to satisfy constraint: Member must not be null\"

**Comment by philss** [comment]
@RandomGuy2020 cool! We got something :D

I have an idea that is to use another HTTP client and log the request/response. Tesla has [this middleware](https://hexdocs.pm/tesla/Tesla.Middleware.Logger.html#module-logger-debug-output) that logs the request, so we can use that to inspect what is going on.  But the process of configuring another HTTP client is not documented yet (it was introduced in #42), so I will try to document it first.

**Comment by RandomGuy2020** [comment]
I want to add the get_policy doesnt work with {:aws, github: "aws-beam/aws-elixir"} they say : The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. 
But it's working on the version 6

**Comment by RandomGuy2020** [comment]
I used the version 6. The input was wrong I had to:
input = %{policyDocument: test} 
with test = Poison.encode!(%{
"Version": "2012-10-17",
"Statement": [
    %{
        "Effect": "Allow",
        "Action": [
            "iot:Publish",
            "iot:Receive"
        ],
        "Resource": [
            "arn:aws:iot:us-west-2:000000000000:topic/topic_1",
            "arn:aws:iot:us-west-2:000000000000:topic/topic_2"
        ]
    },
    %{
        "Effect": "Allow",
        "Action": [
            "iot:Subscribe"
        ],
        "Resource": [
            "arn:aws:iot:us-west-2:000000000000:topicfilter/topic_1",
            "arn:aws:iot:us-west-2:000000000000:topicfilter/topic_2"
        ]
    },
    %{
        "Effect": "Allow",
        "Action": [
            "iot:Connect"
        ],
        "Resource": [
            "arn:aws:iot:us-west-2:000000000000:client/basicPubSub"
        ]
    }
]
})

I put the problem on solve thanks for your time

**Comment by tejpochiraju** [comment]
@RandomGuy2020 - I am getting the same error `The request signature we calculated does not match the signature you provided.` when calling `AWS.IoT.list_things`. 

The client works fine for `AWS.S3` queries. I have been trying a few versions of `aws-elixir` to see which one works but haven't been able to identify one yet. When you refer to `version 6` do you mean the release `0.6.0`?

I will open a new issue if your response does not resolve it.

**Comment by philss** [comment]
@tejpochiraju did you try the version from GitHub (the master branch)?
