### ISSUE TITLE
Access calls for keywords expect the key to be an atom, got: "X-Amz-Function-Error"

### ISSUE THREAD

**Issue by adampash** [aws-beam/aws-elixir#5]
I'm on Elixir 1.6.4, using 0.5.0 of AWS.

I'm trying to use the Lambda portion of this library, and on invoking my function, I'm getting the following error:

`Access calls for keywords expect the key to be an atom, got: "X-Amz-Function-Error"`

It appears to be happening on line 299 here:

https://github.com/aws-beam/aws-elixir/blob/7d543d71802b3f6065d64a699458fb615915ea27/lib/aws/lambda.ex#L297-L309

Headers are coming back like this:

```elixir
[
    {"Date", "Fri, 20 Apr 2018 01:12:50 GMT"},
    {"Content-Type", "application/json"},
    {"Content-Length", "6403"},
    {"Connection", "keep-alive"},
    {"x-amzn-RequestId", "f13a4d8f-4437-11e8-934b-0d4ffde93ad3"},
    {"x-amzn-Remapped-Content-Length", "0"},
    {"X-Amz-Executed-Version", "$LATEST"},
    {"X-Amzn-Trace-Id", "root=1-5ad93e91-a1770ed8f4eed468e857e018;sampled=0"}
  ]
```

Access expects the first item in each tuple to be an atom and won't work w/strings.

The function is being invoked correctly, and the results I expect are coming back from the invocation, but then the function is dying on that error. 

Let me know if I can provide any more information/help.

**Comment by yraithatha** [comment]
@adampash : I too am facing the same problem. Were you able to resolve the issue?

**Comment by jcomellas** [comment]
@adampash If you can, please check if the changes in PR #14 fix this issue.
