### ISSUE TITLE
Format code using mix format & validate

### ISSUE THREAD

**Issue by vrcca** [aws-beam/aws-elixir#50]
Currently there is no .formatter.exs. It would be great to add it, format all the project & validate in our CI that new additions are formatted (See `mix format --check-formatted`).

**Comment by vrcca** [comment]
This is a good first issue! 😄

**Comment by josevalim** [comment]
Most of the files are generated so I would rather make sure the generator is formatting files before writing them down. WDYT?

**Comment by philss** [comment]
Yeah, I agree with José. Maybe this can be an issue for https://github.com/aws-beam/aws-codegen?

**Comment by vrcca** [comment]
I like this too. Though I would setup the formatter here too anyway, given that now we have manually written code such as AWS.HTTPClient and AWS.Request, AWS.Client, and others.

A point of attention when formatting in the generator is that some methods and parameters are dynamically written, so it may not end up formatted as the mix formatter would do. 🤔

Mit freundlichen Grüßen,

Vitor Cavalcanti

**Comment by philss** [comment]
I did fix this at some point in the last months.
Codegen is formatting the files before writing them down, and we also have a check in this project.
The only issue is that formatting config is not shared, so we may have issues in the future. But I think it's OK for now.
Thanks, guys! :purple_heart:
