### ISSUE TITLE
IoT - shadow error

### ISSUE THREAD

**Issue by ulutomaz** [aws-beam/aws-elixir#6]
Hi,

I am trying to get through the configuration of this package. To get to the point where I would be able to get and update the devices shadow, through the REST API. For easier development, I added my self a permission where I has access to all `iot:*` resources.

In my `config/dev.exs` I have a confguration like in Readme.md
```
iex> client = %AWS.Client{access_key_id: "<access-key-id>",
                     secret_access_key: "<secret-access-key>",
                     region: "us-east-1",
                     endpoint: "amazonaws.com"}
```
Then, if i issue a code to initialize this client, I get back response like

```
%AWS.Client{access_key_id: "<secret>", endpoint: "amazonaws.com",
 port: "443", proto: "https", region: "eu-west-1",
 secret_access_key: "<secret>", service: nil}
```

I can even issue a call to list all the things. I get back the result with all the things listed. 

BUT: When I want to get back the shadow of one of the devices, I get back the *error*. 

I call the shadow with 

```
AWS.IoT.DataPlane.get_thing_shadow(Shadow.Client.init_client(), "<thingName>")
```
init_client is just my function... nothing special. 
And I get back `{:error, "Not Found"}` though if I go and search it over the web console I can see it there.

**Comment by fermuch** [comment]
I found the error. `get_url` inside `iot_data.ex` returns an url ending with a slash (`/`). If you remove the slash, everything works.

**Before:**

```elixir
defp get_url(host, url, %{:proto => proto, :port => port}) do
  "#{proto}://#{host}:#{port}#{url}/"
end
```

**After:**

```elixir
defp get_url(host, url, %{:proto => proto, :port => port}) do
  "#{proto}://#{host}:#{port}#{url}"
end
```

**Comment by jcomellas** [comment]
@ulutomaz @fermuch Please check if the changes in PR #14 fix this issue.
