### ISSUE TITLE
I can't see the documentation

### ISSUE THREAD

**Issue by tiagodavi** [aws-beam/aws-elixir#7]
Where can I find an online documentation for it?

Thank You,

Tiago.

MIX_ENV=docs mix docs
** (Mix.Config.LoadError) could not load config config/docs.exs

** (Mix) The task "docs" could not be found. Did you mean "do"?

**Comment by mrallen1** [comment]
The best place for now is: https://hexdocs.pm/aws/api-reference.html

**Comment by tiagodavi** [comment]
Thank You. What is the Amazon S3 Service? 

AWS Storage Gateway Service ?

And I saw the Rekognition and I couldn't understand what kind of input I should pass. 

compare_faces(client, input, options \\ [])

Is there some example of how to use it?

Many Thanks.

**Comment by tiagodavi** [comment]
Sorry. I meant wich kind of library of this package do I have to use to access S3?

**Comment by mrallen1** [comment]
Unfortunately S3 isn't supported in this library at this time.  It's just the services in the docs.

**Comment by tiagodavi** [comment]
I understand. Thank You.

**Comment by jfacorro** [comment]
Support for S3 can be added once there is an implementation for the `rest-xml` protocol as specified [here](https://github.com/aws/aws-sdk-go/blob/master/models/apis/s3/2006-03-01/api-2.json#L8). 

The currently available protocol implementations are `json` and `rest-json`.
