### ISSUE TITLE
normalize_query won't work for s3 select

### ISSUE THREAD

**Issue by joshuataylor** [aws-beam/aws-elixir#81]
[select_object_content](https://github.com/aws-beam/aws-elixir/blob/master/lib/aws/generated/s3.ex#L7093) builds a query string like this:
`select&select-type=2`
[normalize_query](https://github.com/aws-beam/aws-elixir/blob/master/lib/aws/signature.ex#L223) then expects URLs to have = in them, but this doesn't.

This causes the API not to work. So the function needs to be updated to support this edgecase.

I'll take a look at creating a PR for this :+1:

**Comment by philss** [comment]
@joshuataylor good catch! Maybe changing https://github.com/aws-beam/aws-elixir/blob/master/lib/aws/signature.ex#L227 to accept it is enough? I imagine swapping the comma by a cons `|` in the sort function args fixes the problem. WDYT? A PR is welcome!

**Comment by jonatanklosko** [comment]
I believe this should be fixed by #86.

**Comment by philss** [comment]
Yeah, I believe this is fixed. Thanks, @jonatanklosko! :purple_heart: 
@joshuataylor please feel free to re-open if you find any issues.
