### ISSUE TITLE
Release 0.8.0?

### ISSUE THREAD

**Issue by cjbell** [aws-beam/aws-elixir#82]
There are [quite a few changes](https://github.com/aws-beam/aws-elixir/compare/v0.7.0..master) since the last release, notably the fix for #71 which is required to support OTP 24. Could we have a new release published soon, please?

**Comment by philss** [comment]
@cjbell done! Thanks for bringing this. My idea was to release early, but I had to focus on other things.

For this release I had a small problem with the docs - they are too big and couldn't be published - , but I will investigate better tomorrow.

**Comment by cjbell** [comment]
🎉🎉🎉 thanks @philss
