### ISSUE TITLE
ServiceDiscovery discover_instances uses wrong endpoint prefix

### ISSUE THREAD

**Issue by drowzy** [aws-beam/aws-elixir#95]
The endpoint [prefix](https://github.com/aws-beam/aws-elixir/blob/master/lib/aws/generated/service_discovery.ex#L27) works for all service discovery operations except:

* [DiscoverInstances](https://docs.aws.amazon.com/cloud-map/latest/api/API_DiscoverInstances.html)
* [UpdateInstanceCustomHealthStatus](https://docs.aws.amazon.com/cloud-map/latest/api/API_UpdateInstanceCustomHealthStatus.html)

Which for some reason uses `data-discovery` as the endpoint prefix.

**Comment by philss** [comment]
@drowzy sorry for the delay. Would you mind to check again?
I think this is fixed after https://github.com/aws-beam/aws-elixir/pull/147 and the release of `v0.13.0`

**Comment by drowzy** [comment]
No worries! I can't verify since I'm currently not using AWS anymore so I don't have an account 😄. But looking at #147 it seems like it solves this issue :)

**Comment by philss** [comment]
Ohh, I see 😄
Thanks! So I'm closing this one.
